
cc_library(
    name = "Game",
    hdrs = ["Game.h", "Strategy.h"],
    srcs = ["Game.cpp"],
    deps = ["//Board:Board",],
    visibility = ["//MCTS:__pkg__",
                  "//UserPlayer:__pkg__", "//main:__pkg__",],
)
