
cc_library(
    name = "MCTS",
    hdrs = ["MCTS.h", "MAB.h", "TreeNode.h", "UCB1.h", "UtilityNode.h"],
    srcs = ["MCTS.cpp", "TreeNode.cpp"],
    deps = ["//Board:Board", "//Game:Game", "//library:Tools",],
    visibility = ["//main:__pkg__",],
)
