
cc_library(
    name = "Board",
    hdrs = ["Move.h", "Board.h", "BoardTest.h"],
    srcs = ["Board.cpp"],
    visibility = ["//Game:__pkg__", "//MCTS:__pkg__", "//UserPlayer:__pkg__", "//main:__pkg__",],
)
